#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# Copyright (c) 2020, MrDoob
# All rights reserved.
PUID=${PUID:-911}
PGID=${PGID:-911}
if [ ! "$(id -u abc)" -eq "$PUID" ]; then usermod -o -u "$PUID" abc; fi
if [ ! "$(id -g abc)" -eq "$PGID" ]; then groupmod -o -g "$PGID" abc; fi
echo "
GID/UID
------------------------------------------------
User uid:    $(id -u abc)
User gid:    $(id -g abc)
------------------------------------------------
"
chown -R abc:abc /app \
/config
/defaults
