#!/usr/bin/with-contenv bash
# shellcheck shell=bash
if [ -z ${APP_BRANCH+x} ]; then
   echo "APP_BRANCH is unset"
   echo "Default branch: master"
   APP_BRANCH=master
else
   echo "APP_BRANCH is set to '$APP_BRANCH'"
fi

# Fetch site or update existing
if [[ ! -d /traktarr/.git ]]; then
   echo '-----------------------'
   echo '| Installing Traktarr |'
   echo '-----------------------'
   echo "App branch is set to '$APP_BRANCH'"
   git clone -b "$APP_BRANCH" https://github.com/l3uddz/traktarr /"${APP_DIR}"
   echo "** Installing App Requirements **"
   pip3 install --quiet --no-cache-dir --upgrade -r /"${APP_DIR}"/requirements.txt
   ln -s /traktarr/traktarr.py /usr/local/bin/traktarr
   echo "**** cleanup ****"
   rm -rf /root/.cache \
   /tmp/*

elif [[ -d /traktarr/.git ]]; then
   if [[ "$SKIPUPDATE" == "yes" ]] || [[ "$SKIPUPDATE" == "Yes" ]] || [[ "$SKIPUPDATE" == "YES" ]]; then
      echo '-----------------------'
      echo '|   Skipping Update    |'
      echo '-----------------------'
   else
      echo '-----------------------'
      echo '|  Updating Traktarr   |'
      echo '-----------------------'
      echo "APP_BRANCH is set to '$APP_BRANCH'"
      cd /traktarr || return
      git reset --hard origin/"$APP_BRANCH" && git pull origin "$APP_BRANCH"
      pip3 install --quiet --no-cache-dir --upgrade -r /"${APP_DIR}"/requirements.txt
   fi
fi

# Set Permissions
chown -R abc:abc \
/config \
/traktarr
#"
