#!/usr/bin/with-contenv bash

apk update && apk add bash gcc musl-dev \
    python3 python3-dev py3-pip \
    libxslt-dev libxml2-dev py3-virtualenv

python3 -m pip install virtualenv

python3 -m venv /app/tautulli

source /app/tautulli/bin/activate

python3 -m pip install --upgrade pip setuptools pip-tools

echo "**** install packages ****" && \
   python3 -m pip install --upgrade pip && \
   python3 -m pip install --no-warn-script-location --upgrade --force-reinstall --no-deps --user -r /app/tautulli/requirements.txt




