#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# Copyright (c) 2020, MrDoob
# All rights reserved.
function log() {
     echo "[UPLOADER] ${1}"
}

rm -f /dev/null && mknod /dev/null c 1 3 && chmod 666 /dev/null

apk update --quiet --no-cache --no-progress
apk upgrade --quiet --no-cache --no-progress

log "**** install build packages from packages.lock ****"
 INSTALL="/app/requirements.txt"
 while IFS=$'\n' read -r -a myArray; do
     apk add --quiet --no-cache --no-progress ${myArray[0]}
 done < $INSTALL

ARCH="$(command arch)"
if [ "${ARCH}" = "x86_64" ]; then 
  ARCH="amd64"
elif [ "${ARCH}" = "aarch64" ]; then 
  ARCH="arm64" 
elif [ "${ARCH}" = "armv7l" ]; then 
  ARCH="armhf" 
else
  echo "**** Unsupported Linux architecture ${ARCH} found, exiting... ****"
  sleep infinity
fi

## VERSION=1.55.1
VERSION=$(curl -sX GET "https://api.github.com/repos/rclone/rclone/releases/latest" | awk '/tag_name/{print $4;exit}' FS='[""]' | sed -e 's_^v__')
curl --silent -o /tmp/rclone.zip -SL https://github.com/rclone/rclone/releases/download/v${VERSION}/rclone-v${VERSION}-linux-${ARCH}.zip
cd /tmp/ && unzip -q /tmp/rclone.zip && mv /tmp/rclone-*-linux-${ARCH}/rclone /usr/local/bin/

rm -rf /var/cache/apk/* \
      /tmp/rclone-*-linux-${ARCH} >>/dev/null

if [[ ! -d "/app/language" ]]; then mkdir -p /app/language && git -C /app clone https://github.com/dockserver/language.git; fi
   rm -rf /var/run/s6/etc/cont-init.d/90-custom-folders \
      /var/run/s6/etc/cont-init.d/99-custom-files \
      /etc/cont-init.d/90-custom-folders \
      /etc/cont-init.d/99-custom-files >>/dev/null

if [[ ! -d "/system/uploader/json/" ]];then mkdir -p /system/uploader/json/; fi
if [[ ! -d "/system/uploader/json/done/" ]];then mkdir -p /system/uploader/json/done/; fi
if [[ ! -d "/system/uploader/json/upload/" ]];then mkdir -p /system/uploader/json/upload/; fi


if [[ ! -f "/system/servicekeys/rclonegdsa.conf" ]]; then
   log "-->> [ WARNING ] ----------------------------- [ WARNING ] <<--"
   log "-->> [ WARNING ] no rclonegdsa.conf file found [ WARNING ] <<--"
   log "-->> [ WARNING ]         sleeping for 30s      [ WARNING ] <<--"
   log "-->> [ WARNING ] ----------------------------- [ WARNING ] <<--"
   sleep infinity
fi
####
JSONDIR="/system/servicekeys/keys/"
GDSAARRAY=$(ls -l ${JSONDIR} | egrep -c '(GDS|GDSA)')

if [[ ${GDSAARRAY} -lt "1" ]]; then
   log "-->> [ WARNING ] ---------------- [ WARNING ] <<--"
   log "-->> [ WARNING ]  No GDSAS found  [ WARNING ] <<--"
   log "-->> [ WARNING ] ---------------- [ WARNING ] <<--"
   sleep infinity
fi
####
if [[ ! -f "/root/.config/rclone/rclone.conf" ]]; then
   mkdir -p /root/.config/rclone/ && ln -s /system/servicekeys/rclonegdsa.conf /root/.config/rclone/rclone.conf
fi

rm -rf /var/cache/apk/* \
       /etc/nginx/nginx.conf

# Configure nginx
cp -r /conf/nginx.conf /etc/nginx/nginx.conf
cp -r /conf/fpm-pool.conf /etc/php8/php-fpm.d/www.conf
cp -r /conf/php.j2 /etc/php8/conf.d/custom.ini

#E-O-F#
