#!/usr/bin/with-contenv bash
# shellcheck shell=bash
#####################################
# All rights reserved.              #
# started from Zero                 #
# Docker owned dockserver           #
# Docker Maintainer dockserver      #
#####################################
#####################################
# THIS DOCKER IS UNDER LICENSE      #
# NO CUSTOMIZING IS ALLOWED         #
# NO REBRANDING IS ALLOWED          #
# NO CODE MIRRORING IS ALLOWED      #
#####################################
function log() {
     echo "[UPLOADER] ${1}"
}

addgroup -S abc
adduser -S abc -G abc
PGID=${PGID:-1000}
PUID=${PUID:-1000}
groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

echo "----------------------------------------------------

 ____             _                                 
|  _ \  ___   ___| | _____  ___ _ ____   _____ _ __ 
| | | |/ _ \ / __| |/ / __|/ _ \ '__\ \ / / _ \ '__|
| |_| | (_) | (__|   <\__ \  __/ |   \ V /  __/ |   
|____/ \___/ \___|_|\_\___/\___|_|    \_/ \___|_|


----------------------------------------------------"

log "-> Setting Permissions || start <-"
rm -rf /system/uploader/.keys/{usedupload,lastday}
rm -rf /app/uploader/pid/ \
       /system/uploader/vfsforget/ \
       /system/uploader/logs/ \
       /app/uploader/discord \

mkdir -p /system/uploader/json/ \
        /system/uploader/json/{done,upload}

pathglobal=/mnt/downloads
find ${pathglobal} -type f -name '*.lck' -delete

chown -cR abc:abc \
	/app \
	/system/*

chmod -cR 755 /app \
        /system/*

#<E-o-F#
