#!/usr/bin/with-contenv bash
# shellcheck shell=bash
#####################################
# All rights reserved.              #
# started from Zero                 #
# Docker owned dockserver           #
# Docker Maintainer dockserver      #
#####################################
#####################################
# THIS DOCKER IS UNDER LICENSE      #
# NO CUSTOMIZING IS ALLOWED         #
# NO REBRANDING IS ALLOWED          #
# NO CODE MIRRORING IS ALLOWED      #
#####################################
function log() {
     echo "[UPLOADER] ${1}"
}
PUID=${PUID:-1000}
PGID=${PGID:-1000}
if [ ! "$(id -u abc)" -eq "$PUID" ]; then usermod -o -u "$PUID" abc; fi
if [ ! "$(id -g abc)" -eq "$PGID" ]; then groupmod -o -g "$PGID" abc; fi

echo "----------------------------------------------------

 ____             _                                 
|  _ \  ___   ___| | _____  ___ _ ____   _____ _ __ 
| | | |/ _ \ / __| |/ / __|/ _ \ '__\ \ / / _ \ '__|
| |_| | (_) | (__|   <\__ \  __/ |   \ V /  __/ |   
|____/ \___/ \___|_|\_\___/\___|_|    \_/ \___|_|


----------------------------------------------------"


TARGET_FOLDER='/etc/services.d/uploader-tdrive'
FIND=$(which find)
FIND_BASE='-type f'
FIND_FILE='"down"'
FIND_FILE_ACTION='-name'
FIND_MINDEPTH='-mindepth 1'
FIND_ACTION='-delete 1>/dev/null 2>&1'
command="${FIND} ${TARGET_FOLDER} ${FIND_MINDEPTH} ${FIND_FILE_ACTION} ${FIND_FILE} ${FIND_BASE} ${FIND_ACTION}"
eval ${command}
rjson=/system/servicekeys/rclonegdsa.conf
if grep -q GDSA1C "${rjson}" && grep -q GDSA2C "${rjson}"; then
    echo "-->> -------------------- <<--"
    echo "-->    TCRYPT UPLOADER    <<--"
    echo "-->       WILL USED       <<--"
    echo "-->> -------------------- <<--"
else
    echo "-->> -------------------- <<--"
    echo "-->    TDRIVE UPLOADER    <<--"
    echo "-->       WILL USED       <<--"
    echo "-->> -------------------- <<--"
    exit 0
fi

log "-> Setting Permissions || start <-"
mkdir -p /app/uploader/{pid,discord}
if [[ ! -f /system/uploader/.keys/lasteservicekey ]]; then
   touch /system/uploader/.keys/lasteservicekey 1>/dev/null 2>&1
   echo "0" >/system/uploader/.keys/lasteservicekey
fi
if [[ ! -f /system/uploader/.keys/usedupload ]]; then
   touch /system/uploader/.keys/usedupload 1>/dev/null 2>&1
   echo "0" >/system/uploader/.keys/usedupload
fi

if [[ ! -f /system/uploader/.keys/lastday ]]; then
   touch /system/uploader/.keys/lastday 1>/dev/null 2>&1
   echo "0" >/system/uploader/.keys/lastday
fi

if [[ -d /system/uploader/.keys ]]; then
   chown -cR abc:abc /system/uploader/.keys 1>/dev/null 2>&1
fi

#<E-o-F#
