#!/usr/bin/with-contenv bash
# shellcheck shell=bash
#####################################
# All rights reserved.              #
# started from Zero                 #
# Docker owned dockserver           #
# Docker Maintainer dockserver      #
#####################################
#####################################
# THIS DOCKER IS UNDER LICENSE      #
# NO CUSTOMIZING IS ALLOWED         #
# NO REBRANDING IS ALLOWED          #
# NO CODE MIRRORING IS ALLOWED      #
#####################################
function log() {
     echo "${1}"
}

addgroup -S abc
adduser -S abc -G abc
PGID=${PGID:-1000}
PUID=${PUID:-1000}
groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

echo "----------------------------------------------------

 ____             _                                 
|  _ \  ___   ___| | _____  ___ _ ____   _____ _ __ 
| | | |/ _ \ / __| |/ / __|/ _ \ '__\ \ / / _ \ '__|
| |_| | (_) | (__|   <\__ \  __/ |   \ V /  __/ |   
|____/ \___/ \___|_|\_\___/\___|_|    \_/ \___|_|


----------------------------------------------------"

log "-> Setting Permissions || start <-"
rm -rf /system/uploader/.keys/{usedupload,lastday} \
       /app/uploader/{pid,discord} \
       /system/uploader/vfsforget/ 

mkdir -p /system/uploader/.keys \
         /system/uploader/{logs,json} \
         /system/uploader/json/{done,upload}

global=/mnt/downloads
find ${global} -type f -name '*.lck' -delete
chown -cR abc:abc /app /system/* > /dev/null
chmod -cR 755 /app /system/* > /dev/null

UAGENT=${UAGENT:-null}
if [[ ${UAGENT} == 'null' ]]; then
   UAGENT=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
   USERAGENT=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
else
   UAGENT=${UAGENT}
   USERAGENT=${USERAGENT}
fi

sample=/app/uploader/.sample.uploader.env
uploaderenv=/system/uploader/uploader.env
if [[ -f ${uploaderenv} ]]; then
   source $uploaderenv
   echo -e "#-------------------------------------------------------
#   UPLOADER ENVIROMENTS
#-------------------------------------------------------
## USER VALUES
PUID=${PUID:-1000}
PGID=${PGID:-1000}

## RCLONE - SETTINGS
BANDWITHLIMIT=${BANDWITHLIMIT:-null}
LOG_LEVEL=${LOG_LEVEL:-INFO}
USERAGENT=${USERAGENT}
DLFOLDER=${DLFOLDER:-/mnt/downloads}

## USER - SETTINGS
DRIVEUSEDSPACE=${DRIVEUSEDSPACE:-null}
MIN_AGE_FILE={MIN_AGE_FILE:-10m}
#-------------------------------------------------------
#   UPLOADER ENVIROMENTS
#-------------------------------------------------------" >$uploaderenv
else
   cp ${sample} ${uploaderenv}
fi

#E-O-F
