#!/usr/bin/with-contenv bash
# shellcheck shell=bash
#####################################
# All rights reserved.              #
# started from Zero                 #
# Docker owned dockserver           #
# Docker Maintainer dockserver      #
#####################################
#####################################
# THIS DOCKER IS UNDER LICENSE      #
# NO CUSTOMIZING IS ALLOWED         #
# NO REBRANDING IS ALLOWED          #
# NO CODE MIRRORING IS ALLOWED      #
#####################################
function log() {
     echo "${1}"
}

addgroup -S abc
adduser -S abc -G abc
PGID=${PGID:-1000}
PUID=${PUID:-1000}
groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

if [[ -f /dockserver.txt ]]; then cat /dockserver.txt ; fi
echo '
-------------------------------------
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------
"

   cat > /etc/apk/repositories << EOF; $(echo)
http://dl-cdn.alpinelinux.org/alpine/v$(cat /etc/alpine-release | cut -d'.' -f1,2)/main
http://dl-cdn.alpinelinux.org/alpine/v$(cat /etc/alpine-release | cut -d'.' -f1,2)/community
http://dl-cdn.alpinelinux.org/alpine/edge/testing
EOF

   apk --quiet --no-progress update && \
   apk --quiet --no-progress upgrade

   cat /app/requirements.txt | while IFS=$'\n' read -ra myArray; do
      apk add --quiet --no-progress --update ${myArray[@]}
   done

ARCH="$(command arch)"
if [ "${ARCH}" = "x86_64" ]; then
   export ARCH="amd64"
elif [ "${ARCH}" = "aarch64" ]; then
     export ARCH="arm64"
elif [ "${ARCH}" = "armv7l" ]; then
     export ARCH="armhf"
else
    echo "**** Unsupported Linux architecture ${ARCH} found, exiting... ****" && exit 1
fi

apk add --quiet --no-cache --no-progress --virtual=build-dependencies aria2 curl findutils coreutils unzip jq
VERSION=$(curl -sX GET "https://api.github.com/repos/rclone/rclone/releases/latest" | awk '/tag_name/{print $4;exit}' FS='[""]' | sed -e 's_^v__')
aria2c -x2 -k1M -d /tmp -o rclone.zip https://github.com/rclone/rclone/releases/download/v${VERSION}/rclone-v${VERSION}-linux-${ARCH}.zip && \
cd /tmp/ && unzip -q /tmp/rclone.zip
mv /tmp/rclone-*-linux-${ARCH}/rclone /usr/local/bin/
apk del --quiet --purge build-dependencies && \
echo "**** cleanup ****" && \
rm -rf /var/cache/apk/* /tmp/*

if [[ ! -f "/system/servicekeys/rclonegdsa.conf" ]]; then
   log "-->> [ WARNING ] ----------------------------- [ WARNING ] <<--"
   log "-->> [ WARNING ] no rclonegdsa.conf file found [ WARNING ] <<--"
   log "-->> [ WARNING ]         sleeping for 30s      [ WARNING ] <<--"
   log "-->> [ WARNING ] ----------------------------- [ WARNING ] <<--"
   sleep infinity
fi

CONF=/system/servicekeys/rclonegdsa.conf
if `rclone config show --config=${CONF} | grep "GDSA" &>/dev/null`;then
  KEY="GDSA"
elif `rclone config show --config=${CONF} | head -n1 | grep -Po '\[.*?]' | sed 's/.*\[\([^]]*\)].*/\1/' | sed '/GDSA/d'`;then
  KEY=""
else
   log "-->> [ WARNING ] ----------------- [ WARNING ] <<--"
   log "-->> [ WARNING ]  no match found   [ WARNING ] <<--"
   log "-->> [ WARNING ]  of GDSA[01=~100] [ WARNING ] <<--"
   log "-->> [ WARNING ]    or [01=~100]   [ WARNING ] <<--"
   log "-->> [ WARNING ] ----------------- [ WARNING ] <<--"
   sleep infinity
fi

KEYLOCAL=/system/servicekeys/keys/
ARRAY=$(ls -A ${KEYLOCAL} | wc -l )
if [[ "${ARRAY}" -eq "0" ]]; then
   log "-->> [ WARNING ] ----------------- [ WARNING ] <<--"
   log "-->> [ WARNING ]  no match found   [ WARNING ] <<--"
   log "-->> [ WARNING ]  of GDSA[01=~100] [ WARNING ] <<--"
   log "-->> [ WARNING ]    or [01=~100]   [ WARNING ] <<--"
   log "-->> [ WARNING ] ----------------- [ WARNING ] <<--"
   sleep infinity
fi

rm -rf /var/cache/apk/*

cp -r /conf/nginx.conf /etc/nginx/nginx.conf
cp -r /conf/fpm-pool.conf /etc/php8/php-fpm.d/www.conf
cp -r /conf/php.j2 /etc/php8/conf.d/custom.ini
cp -r ${CONF} /root/.config/rclone/rclone.conf

rm -rf /system/uploader/.keys/{usedupload,lastday} \
       /app/uploader/{pid,discord} \
       /system/uploader/vfsforget/ 

mkdir -p /system/uploader/.keys \
         /system/uploader/{logs,json} \
         /system/uploader/json/{done,upload}

USERAGENT=${USERAGENT:-null}
if [[ ${USERAGENT} == 'null' ]]; then
   USERAGENT=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
fi

global=/mnt/downloads
find ${global} -type f -name '*.lck' -delete
chown -cR abc:abc /app /system/* > /dev/null
chmod -cR 755 /app /system/* > /dev/null
chown -cR abc:abc /root/.config/ > /dev/null

sample=/app/uploader/.sample.uploader.env
uploaderenv=/system/uploader/uploader.env
if [[ -f ${uploaderenv} ]]; then
source $uploaderenv
echo -e "#-------------------------------------------------------
#   UPLOADER ENVIROMENTS
#-------------------------------------------------------
## USER VALUES
PUID=${PUID:-1000}
PGID=${PGID:-1000}

## RCLONE - SETTINGS
BANDWITHLIMIT=${BANDWITHLIMIT:-40}
LOG_LEVEL=${LOG_LEVEL:-INFO}
DLFOLDER=${DLFOLDER:-/mnt/downloads}
USERAGENT=${USERAGENT}

## USER - SETTINGS
DRIVEUSEDSPACE=${DRIVEUSEDSPACE:-10}
MIN_AGE_FILE=${MIN_AGE_FILE:-10m}
#-------------------------------------------------------
#   UPLOADER ENVIROMENTS
#-------------------------------------------------------" >$uploaderenv
else
source $sample
echo -e "#-------------------------------------------------------
#   UPLOADER ENVIROMENTS
#-------------------------------------------------------
## USER VALUES
PUID=${PUID:-1000}
PGID=${PGID:-1000}

## RCLONE - SETTINGS
BANDWITHLIMIT=${BANDWITHLIMIT:-40}
LOG_LEVEL=${LOG_LEVEL:-INFO}
DLFOLDER=${DLFOLDER:-/mnt/downloads}
USERAGENT=${USERAGENT}

## USER - SETTINGS
DRIVEUSEDSPACE=${DRIVEUSEDSPACE:-10}
MIN_AGE_FILE=${MIN_AGE_FILE:-10m}
#-------------------------------------------------------
#   UPLOADER ENVIROMENTS
#-------------------------------------------------------" >$uploaderenv
fi

apk add --quiet --no-progress --update coreutils
mkdir -p /root/.config/rclone/
mount --bind /app/rclone/ /root/.config/rclone/

echo "------------------------------
    _____   _   _  __  __
   |_   _| | | | | \ \/ /
     | |   | |_| |  \  / 
     | |   |  _  |  /  \ 
     |_|   |_| |_| /_/\_\

------------------------------
     to all the coders

We have take some code from :

  88lex , RTRO , edrock200
 ChaoticWeg & linuxserver.io

       and all other
  If we missed you, sorry..

------------------------------"
