#!/usr/bin/with-contenv bash
# shellcheck shell=bash
#####################################
# All rights reserved.              #
# started from Zero                 #
# Docker owned dockserver           #
# Docker Maintainer dockserver      #
#####################################
#####################################
# THIS DOCKER IS UNDER LICENSE      #
# NO CUSTOMIZING IS ALLOWED         #
# NO REBRANDING IS ALLOWED          #
# NO CODE MIRRORING IS ALLOWED      #
#####################################

function log() {
   echo "[MOUNT] ${1}"
}
PUID=${PUID:-1000}
PGID=${PGID:-1000}
if [ ! "$(id -u abc)" -eq "$PUID" ]; then usermod -o -u "$PUID" abc; fi
if [ ! "$(id -g abc)" -eq "$PGID" ]; then groupmod -o -g "$PGID" abc; fi
echo "
----------------------------------------------------
 ____             _                                 
|  _ \  ___   ___| | _____  ___ _ ____   _____ _ __ 
| | | |/ _ \ / __| |/ / __|/ _ \ '__\ \ / / _ \ '__|
| |_| | (_) | (__|   <\__ \  __/ |   \ V /  __/ |   
|____/ \___/ \___|_|\_\___/\___|_|    \_/ \___|_|


----------------------------------------------------
     GID/UID
----------------------------------------------------
     User uid:    ${PUID}
     User gid:    ${PGID}
----------------------------------------------------
"
log "-> Setting Permissions || start <-"
folder="/system/rclone /app /root"
for i in ${folder}; do
   find $i -exec chmod a=rx,u+w {} \;
   find $i -exec chown -hR abc:abc {} \;
   chown -cf abc:abc /root
done
log "-> Setting Permissions & Folder || done <-"

drivespace=$(df -BG /mnt --local | tail -n +2 | awk '{print $4}' | sed -e 's/G//g')
checkspace=$(echo $(((${drivespace}) / 4 | bc)) | sed -r 's/([^0-9]*([0-9]*)){1}.*/\2/')
VFS_CACHE_MAX_SIZE=${VFS_CACHE_MAX_SIZE:-null}
if [[ ${VFS_CACHE_MAX_SIZE} == 'null' ]]; then
   VFS_CACHE_MAX_SIZE=${checkspace}G
else
   VFS_CACHE_MAX_SIZE=${VFS_CACHE_MAX_SIZE}
   sed -i "s#VFS_CACHE_MAX_SIZE=G#VFS_CACHE_MAX_SIZE=50G#g" /system/mount/mount.env
fi
UAGENT=${UAGENT:-null}
if [[ ${UAGENT} == 'null' ]]; then
   UAGENT=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
else
   UAGENT=${UAGENT}
fi
RC_PASSWORD=${RC_PASSWORD:-null}
if [[ ${RC_PASSWORD} == 'null' ]]; then
   RC_PASSWORD=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1)
else
   RC_PASSWORD=${RC_PASSWORD}
fi

## migration to new once
rcloneenv=/system/mount/mount.env
rclonetmp=/tmp/mount.env
rclonesample=/app/env/sample.env

if [[ ! -f ${rcloneenv} ]]; then
   mv ${rclonesample} ${rclonetmp}
else
   mv ${rcloneenv} ${rclonetmp}
fi

source ${rclonetmp}
echo -e "#!/usr/bin/with-contenv bash
# shellcheck shell=bash
#####################################
# All rights reserved.              #
# started from Zero                 #
# Docker owned dockserver           #
# Docker Maintainer dockserver      #
#####################################
#####################################
# THIS DOCKER IS UNDER LICENSE      #
# NO CUSTOMIZING IS ALLOWED         #
# NO REBRANDING IS ALLOWED          #
# NO CODE MIRRORING IS ALLOWED      #
#####################################
# shellcheck disable=SC2086
# shellcheck disable=SC2006

#-------------------------------------------------------
#   MOUNT ENVIRONMENT
#-------------------------------------------------------
## USER VALUES
PUID=${PUID:-1000}
PGID=${PGID:-1000}
TIMEZONE=${TZ:-UTC}

## CRITICAL SETUP FOR CRYPT USER
HASHPASSWORD=${HASHPASSWORD:-hashed}

## MERGERFS ADDITIONAL FOLDER
ADDITIONAL_MOUNT=${ADDITIONAL_MOUNT:-null}
ADDITIONAL_MOUNT_PERMISSION=${ADDITIONAL_MOUNT_PERMISSION:-RW}

## RCLONE - SETTINGS
CACHE_INFO_AGE=${CACHE_INFO_AGE:-6h}
POLL_INTERVAL=${POLL_INTERVAL:-1m}
UMASK=${UMASK:-022}
DRIVETRASH=${DRIVETRASH:-false}
DIR_CACHE_TIME=${DIR_CACHE_TIME:-12h}
DRIVE_CHUNK_SIZE=${DRIVE_CHUNK_SIZE:-128M}
BUFFER_SIZE=${BUFFER_SIZE:-32M}
TMPRCLONE=${TMPRCLONE:-/mnt/rclone_cache}
UAGENT=${UAGENT}
TPSLIMIT=${TPSLIMIT:-10}
TPSBURST=${TPSBURST:-10}

## VFS - SETTINGS
VFS_CACHE_POLL_INTERVAL=${VFS_CACHE_POLL_INTERVAL:-2m}
VFS_READ_CHUNK_SIZE=${VFS_READ_CHUNK_SIZE:-128M}
VFS_CACHE_MAX_AGE=${VFS_CACHE_MAX_AGE:-6h}
VFS_READ_CHUNK_SIZE_LIMIT=${VFS_READ_CHUNK_SIZE_LIMIT:-4096M}
VFS_CACHE_MODE=${VFS_CACHE_MODE:-full}
VFS_CACHE_MAX_SIZE=${VFS_CACHE_MAX_SIZE}
VFS_REFRESH=${VFS_REFRESH:-12h}

## LOG - SETTINGS
LOGLEVEL=${LOGLEVEL:-INFO}
LOGLEVEL_RC=${LOGLEVEL_RC:-INFO}

## RC-CONTROLLE
RC_ADDRESS=${RC_ADDRESS:-5572}
RC_USER=${RC_USER:-rclone}
RC_PASSWORD=${RC_PASSWORD}

## DISCORD
DISCORD_SEND=${DISCORD_SEND:-null}
DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL:-null}
DISCORD_EMBED_TITEL=${DISCORD_EMBED_TITEL:-MOUNT_INFORMATIONS}
DISCORD_ICON_OVERRIDE=${DISCORD_ICON_OVERRIDE:-https://i.imgur.com/MZYwA1I.png}
DISCORD_NAME_OVERRIDE=${DISCORD_NAME_OVERRIDE:-MOUNT}

## NZB CLEANUP-CONTROLLE
NZBCLEANUP=${NZBCLEANUP:-false}
DRIVEUSEDPERCENT=${DRIVEUSEDPERCENT:-75}
NZBBACKUPFOLDER=${NZBBACKUPFOLDER:-/mnt/nzb}
NZBBACKUPTIME=${NZBBACKUPTIME:-240}
NZBDOWNLOADFOLDER=${NZBDOWNLOADFOLDER:-/mnt/downloads/nzb}
NZBDOWNLOADFOLDERTIME=${NZBDOWNLOADFOLDERTIME:-10800}

## LANGUAGE MESSAGES
LANGUAGE=${LANGUAGE:-en}

#-------------------------------------------------------
#   MOUNT ENVIRONMENT
#-------------------------------------------------------" >${rcloneenv}

if [[ -f ${rclonetmp} ]]; then
   rm -f ${rclonetmp}
fi

source ${rcloneenv}
if [[ ! -d ${TMPRCLONE} ]]; then mkdir -p ${TMPRCLONE} && chown -hR abc:abc ${TMPRCLONE} && chmod -R 775 ${TMPRCLONE}; fi
if [[ ! -d "/mnt/remotes" ]]; then mkdir -p /mnt/remotes && chown -hR abc:abc /mnt/remotes && chmod -R 775 /mnt/remotes; fi
if [[ ! -d "/mnt/unionfs" ]]; then mkdir -p ${SUNION} && chown -hR abc:abc ${SUNION} && chmod -R 775 ${SUNION}; fi
if [[ ! -d "/mnt/downloads" ]]; then mkdir -p ${SDOWN} && chown -hR abc:abc ${SDOWN} && chmod -R 775 ${SDOWN}; fi

#<EOF>#
