#!/usr/bin/with-contenv bash

while true; do
   if mountpoint -q "/mnt/unionfs"; then
      break
   else
     sleep 5
   fi
done

cd /app/radarr/bin || exit

exec \
    s6-setuidgid abc /app/radarr/bin/Radarr \
    -nobrowser -data=/config
