#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Copyright (c) 2020, MrDoob
# All rights reserved.

# shellcheck disable=SC2086
umask 022
command="/app/tdrive/uploader.sh"
echo "-> Starting tdrive Uploader <-"
exec $command
