#!/usr/bin/with-contenv bash
#####################################
# All rights reserved.              #
# started from Zero                 #
# Docker owned dockserver           #
# Docker Maintainer dockserver      #
#####################################
#####################################
# THIS DOCKER IS UNDER LICENSE      #
# NO CUSTOMIZING IS ALLOWED         #
# NO REBRANDING IS ALLOWED          #
# NO CODE MIRRORING IS ALLOWED      #
#####################################
umask 022
while true; do
   if mountpoint -q "/mnt/unionfs"; then
      break
   else
     sleep 5
   fi
done
chown -cR abc:abc /root /app /system/* &>/dev/null
chmod -cR 755 /root /app /system/* &>/dev/null
command="/app/uploader/uploader.sh"
echo "-> Starting Multi Thread Uploader <-"
exec s6-setuidgid abc $command
