#!/usr/bin/with-contenv bash
# shellcheck shell=bash
#####################################
# All rights reserved.              #
# started from Zero                 #
# Docker owned dockserver           #
# Docker Maintainer dockserver      #
#####################################
#####################################
# THIS DOCKER IS UNDER LICENSE      #
# NO CUSTOMIZING IS ALLOWED         #
# NO REBRANDING IS ALLOWED          #
# NO CODE MIRRORING IS ALLOWED      #
#####################################
function log() {
    echo "[Mount] ${1}"
}
umask 022
vfsforget="/app/vfs/vfsforget.sh"
sleep 2
log "-> Starting vfs/forget in auto mode <-"
exec $vfsforget
#<EOF>#