#!/usr/bin/with-contenv bash
# shellcheck shell=bash
#####################################
# All rights reserved.              #
# started from Zero                 #
# Docker owned dockserver           #
# Docker Maintainer dockserver      #
#####################################
#####################################
# THIS DOCKER IS UNDER LICENSE      #
# NO CUSTOMIZING IS ALLOWED         #
# NO REBRANDING IS ALLOWED          #
# NO CODE MIRRORING IS ALLOWED      #
#####################################
PUID=${PUID:-1000}
PGID=${PGID:-1000}
groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

echo "----------------------------------------------------

 ____             _                                 
|  _ \  ___   ___| | _____  ___ _ ____   _____ _ __ 
| | | |/ _ \ / __| |/ / __|/ _ \ '__\ \ / / _ \ '__|
| |_| | (_) | (__|   <\__ \  __/ |   \ V /  __/ |   
|____/ \___/ \___|_|\_\___/\___|_|    \_/ \___|_|


----------------------------------------------------"
  
 if [[ -f "/donate.txt" ]]; then rm -rf donate.txt;fi

 if [[ ! -d "/app" ]]; then mkdir -p /app 1>/dev/null 2>&1;fi && \
 if [[ ! -d "/defaults" ]]; then mkdir -p /defaults 1>/dev/null 2>&1;fi && \
 if [[ ! -d "/config" ]]; then mkdir -p /config 1>/dev/null 2>&1;fi

 if [[ -d "/app" ]]; then chown -cR abc:abc /app 1>/dev/null 2>&1;fi && \
 if [[ -d "/config" ]]; then chown -cR abc:abc /config 1>/dev/null 2>&1;fi && \
 if [[ -d "/defaults" ]]; then chown -cR abc:abc /defaults 1>/dev/null 2>&1;fi

#E-O-F#
