#!/usr/bin/with-contenv bash

# create folders
if [ ! -d "${PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR}" ]; then \
mkdir -p "${PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR}"
chown -R abc:abc /config
fi

# check Library permissions
PUID=${PUID:-911}
if [ ! "$(stat -c %u /config/Library)" = "$PUID" ]; then
   chown abc:abc -R /config/Library
fi

# remove plex pid after unclean stop
[[ -f "/config/Library/Application Support/Plex Media Server/plexmediaserver.pid" ]] && \
  rm -f "/config/Library/Application Support/Plex Media Server/plexmediaserver.pid"

# permissions (non-recursive) on config root and folders
chown abc:abc \
	/config \
	/config/*
