#!/usr/bin/env bash
# shellcheck shell=bash
#####################################
# All rights reserved.              #
# started from Zero                 #
# Docker owned dockserver           #
# Docker Maintainer dockserver      #
#####################################
#####################################
# THIS DOCKER IS UNDER LICENSE      #
# NO CUSTOMIZING IS ALLOWED         #
# NO REBRANDING IS ALLOWED          #
# NO CODE MIRRORING IS ALLOWED      #
#####################################

export DEBIAN_FRONTEND=noninteractive
echo "**** update system  ****" && \
   apt-get -yqq update 1>/dev/null 2>&1 && \
   apt-get -yqq upgrade 1>/dev/null 2>&1

echo "**** install dependencies ****" && \
   apt-get -yqq install sqlite python pip 1>/dev/null 2>&1

echo "**** python dependencies ****" && \
   pip3 install requests 1>/dev/null 2>&1




