#!/usr/bin/with-contenv bash
# shellcheck shell=bash
#####################################
# All rights reserved.              #
# started from Zero                 #
# Docker owned dockserver           #
# Docker Maintainer dockserver      #
#####################################
#####################################
# THIS DOCKER IS UNDER LICENSE      #
# NO CUSTOMIZING IS ALLOWED         #
# NO REBRANDING IS ALLOWED          #
# NO CODE MIRRORING IS ALLOWED      #
#####################################

FILE="/config/plex.env"

if [[ -f $FILE ]];then
   rm -rf $FILE
fi
if [[ ! -f $FILE ]]; then

echo -e "GenerateChapterThumbBehavior|never
LoudnessAnalysisBehavior|never
MinutesAllowedPaused|10
DlnaReportTimeline|10
TranscodeCountLimit|0
TranscoderH264BackgroundPreset|faster
TranscoderThrottleBuffer|200
ScannerLowPriority|1
ManualPortMappingMode|1
autoEmptyTrash|1
RelayEnabled|0
GenerateBIFFrameInterval|10
secureConnections|1
DlnaEnabled|0
TranscoderCanOnlyRemuxVideo|0
TranscoderToneMapping|1
GenerateIntroMarkerBehavior|never" >"${FILE}"

fi

#E-o-L#
