#!/usr/bin/with-contenv bash
# shellcheck shell=bash
#####################################
# All rights reserved.              #
# started from Zero                 #
# Docker owned dockserver           #
# Docker Maintainer dockserver      #
#####################################
#####################################
# THIS DOCKER IS UNDER LICENSE      #
# NO CUSTOMIZING IS ALLOWED         #
# NO REBRANDING IS ALLOWED          #
# NO CODE MIRRORING IS ALLOWED      #
#####################################
# shellcheck disable=SC2086
# shellcheck disable=SC2002
# shellcheck disable=SC2006
#####################################
if [[ -f "/etc/cont-init.d/87-*" ]]; then
   rm -rf /etc/cont-init.d/87-*
fi
FILE="/config/plex.env"
if [[ -f $FILE ]]; then
   rm -rf $FILE
fi

INSTALL=/requirements.txt
while IFS=$'|' read -r -a myArray; do
  apt-get install -yqq ${myArray[0]}
done <$INSTALL

#####################################
# shellcheck disable=SC2086
# shellcheck disable=SC2002
# shellcheck disable=SC2006
#####################################
#####################################
# NO WAY TO STEAL CODE              #
# Nothing to see here               #
# PUTAS sbox /mha / Pandaura        #
#    ich kacke auf euren Code       #
#####################################
