#!/usr/bin/with-contenv bash

export \
    JELLYFIN_DATA_DIR="/config/data" \
    JELLYFIN_CONFIG_DIR="/config" \
    JELLYFIN_LOG_DIR="/config/log" \
    JELLYFIN_CACHE_DIR="/config/cache"

while true; do
  if [ "$(ls -A /mnt/remotes)" ] && [ "$(ls -A /mnt/unionfs)" ]; then
      break 
   else
      sleep 5 && continue 
   fi
done

exec \
    s6-setuidgid abc /usr/bin/jellyfin \
    --ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg \
    --webdir=/usr/share/jellyfin/web
