#!/usr/bin/with-contenv bash

# cd /app/lidarr/bin || exit

while true; do
  if [ "$(ls -A /mnt/remotes)" ] && [ "$(ls -A /mnt/unionfs)" ]; then
      break 
   else
      sleep 5 && continue 
   fi
done

exec \
    s6-setuidgid abc /app/lidarr/bin/Lidarr \
    -nobrowser -data=/config
