#!/usr/bin/with-contenv bash
while true; do
   if mountpoint -q "/mnt/unionfs"; then
      break
   else
     sleep 5
   fi
done

cd /app/sonarr/bin || exit

exec \
    s6-setuidgid abc mono --debug Sonarr.exe \
    -nobrowser -data=/config
