#!/usr/bin/with-contenv bash
while true; do
  if [ "$(ls -A /mnt/remotes)" ] && [ "$(ls -A /mnt/unionfs)" ]; then
      break 
   else
      sleep 5 && continue 
   fi
done

cd /app/sonarr/bin || exit

exec \
    s6-setuidgid abc mono --debug Sonarr.exe \
    -nobrowser -data=/config
