name: Update Contributors
on:
  workflow_run:
    workflows: ["Get latest versions"]
    types:
      - completed

jobs:
  add-contributors:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.CR_PAT }}
        fetch-depth: 0

    - uses: BobAnkh/add-contributors@master
      with:
        REPO_NAME: 'dockserver/container'
        CONTRIBUTOR: '### Contributors'
        COLUMN_PER_ROW: '4'
        ACCESS_TOKEN: ${{ secrets.CR_PAT }}
        IMG_WIDTH: '50'
        FONT_SIZE: '14'
        PATH: '/README.md'
        COMMIT_MESSAGE: 'docs(README): update contributors'
        AVATAR_SHAPE: 'round'
